
/*atualizar atualizar atualizar*/
/*atualizar atualizar atualizar*/
DB_SEU_NOME para DB_SEU_NOME;
/*atualizar atualizar atualizar*/
/*atualizar atualizar atualizar*/

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_DB_SEU_NOME;

USE DATABASE DB_SEU_NOME;

CREATE OR REPLACE SCHEMA DAGS;
USE SCHEMA DAGS;


--O QUE SÃO STREAMES? 
CREATE OR REPLACE TABLE BRONZE_TB( ID INT IDENTITY, NOME VARCHAR);
CREATE OR REPLACE TABLE SILVER_TB( ID INT IDENTITY, NOME VARCHAR);

CREATE OR REPLACE STREAM STREAM_TB_BRONZE ON TABLE BRONZE_TB;

--Ambos objetos estão vazios
select * from BRONZE_TB;
select * from STREAM_TB_BRONZE;

--Se inserirmos um dado na camada bronze
insert into BRONZE_TB (nome) values ('dhiego');

--Como estão os objetos agora?
select * from BRONZE_TB;
select * from STREAM_TB_BRONZE;

--o dado avança no pipeline
MERGE INTO SILVER_TB AS target  
USING STREAM_TB_BRONZE AS source       
   ON target.NOME = source.NOME         
WHEN MATCHED THEN
    UPDATE SET
        target.NOME = source.NOME 
WHEN NOT MATCHED THEN
    INSERT (
        NOME
    )
    VALUES (
        source.NOME
    );

--Vamos validar os objetos (CDC e Tabelas)
    select * from SILVER_TB;--Dado já disponível na Silver
    select * from BRONZE_TB;--tabela bronze
    select * from STREAM_TB_BRONZE;--como está o stream?
    
insert into BRONZE_TB (nome) values ('Sandra'), ('Renato'), ('Alexandre');




--TASks
--Exemplo mais real com tasks (detalhes no 0.setup)

--Stage Dados
CREATE OR REPLACE TASK DAGS.DADOS_BRUTOS
SCHEDULE = '999 MINUTE'
AS
CALL USP_FORMATA_TB()
;


--bronze
CREATE OR REPLACE TASK DAGS.BRONZE_TB
AFTER DAGS.DADOS_BRUTOS
AS
    CALL USP_FORMATA_TB()
;

--SILVER
CREATE OR REPLACE TASK DAGS.SILVER_TRANSACOES
USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
AFTER DAGS.BRONZE_TB
--WHEN
    --SYSTEM$STREAM_HAS_DATA('BRONZE.STREAM_BRONZE_1')
as
    CALL USP_FORMATA_TB()
;


CREATE OR REPLACE TASK DAGS.SILVER_OPERACOES
USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
AFTER DAGS.BRONZE_TB
--WHEN
    --SYSTEM$STREAM_HAS_DATA('BRONZE.STREAM_BRONZE_2')
as
    CALL USP_FORMATA_TB()
;


CREATE OR REPLACE TASK DAGS.SILVER_APROVACOES
USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
AFTER DAGS.BRONZE_TB
AS
    CALL USP_FORMATA_TB()
;



--GOLD
CREATE OR REPLACE TASK DAGS.GOLD_CONSOLIDACAO
AFTER DAGS.SILVER_APROVACOES
AS
    CALL USP_FORMATA_TB()
;


--HABILITA TASKS
ALTER TASK DAGS.BRONZE_TB RESUME;
ALTER TASK DAGS.SILVER_TRANSACOES RESUME;
ALTER TASK DAGS.SILVER_OPERACOES RESUME;
ALTER TASK DAGS.SILVER_APROVACOES RESUME;
ALTER TASK DAGS.GOLD_CONSOLIDACAO RESUME;
ALTER TASK DAGS.DADOS_BRUTOS RESUME;



--FORÇA EXECUÇÃO
EXECUTE TASK DAGS.DADOS_BRUTOS; 




--RESET
CREATE OR REPLACE STREAM BRONZE.STREAM_BRONZE_1 ON TABLE BRONZE.STAGING;
CREATE OR REPLACE STREAM BRONZE.STREAM_BRONZE_2 ON TABLE BRONZE.STAGING;
CREATE OR REPLACE STREAM BRONZE.STREAM_BRONZE_3 ON TABLE BRONZE.STAGING;

--SUSPENDE TASKS
ALTER TASK DAGS.DADOS_BRUTOS SUSPEND;
ALTER TASK DAGS.BRONZE_TB SUSPEND;
ALTER TASK DAGS.SILVER_TRANSACOES SUSPEND;
ALTER TASK DAGS.SILVER_OPERACOES SUSPEND;
ALTER TASK DAGS.SILVER_APROVACOES SUSPEND;
ALTER TASK DAGS.GOLD_CONSOLIDACAO SUSPEND;

