
/*atualizar atualizar atualizar*/
/*atualizar atualizar atualizar*/
DB_DHIEGO para DB_SEU_NOME;
/*atualizar atualizar atualizar*/
/*atualizar atualizar atualizar*/

USE ROLE ACCOUNTADMIN;

USE DATABASE DB_DHIEGO;

CREATE OR REPLACE SCHEMA DAGS;
USE SCHEMA DAGS;


--O QUE SÃO STREAMES? 
CREATE OR REPLACE TABLE BRONZE_TB( ID INT IDENTITY, NOME VARCHAR);
CREATE OR REPLACE TABLE SILVER_TB( ID INT IDENTITY, NOME VARCHAR);

CREATE OR REPLACE STREAM STREAM_TB_BRONZE ON TABLE BRONZE_TB;

--Ambos objetos estão vazios
select * from BRONZE_TB;
select * from STREAM_TB_BRONZE;

--Se inserirmos um dado na camada bronze
insert into BRONZE_TB (nome) values ('dhiego');

--Como estão os objetos agora?
select * from BRONZE_TB;
select * from STREAM_TB_BRONZE;

--o dado avança no pipeline
MERGE INTO SILVER_TB AS target  
USING STREAM_TB_BRONZE AS source       
   ON target.NOME = source.NOME         
WHEN MATCHED THEN
    UPDATE SET
        target.NOME = source.NOME 
WHEN NOT MATCHED THEN
    INSERT (
        NOME
    )
    VALUES (
        source.NOME
    );

--Vamos validar os objetos (CDC e Tabelas)
    select * from SILVER_TB;--Dado já disponível na Silver
    select * from BRONZE_TB;--tabela bronze
    select * from STREAM_TB_BRONZE;--como está o stream?
    
insert into BRONZE_TB (nome) values ('Sandra'), ('Renato'), ('Alexandre');




--TASks
--Exemplo mais real com tasks (detalhes no 0.setup)

--Stage Dados
CREATE OR REPLACE TASK DAGS.DADOS_BRUTOS
SCHEDULE = '999 MINUTE'
AS
CALL PUBLIC.SIMULATE_KAFKA_STREAM('@BRONZE.DADOS_BRUTOS/', 'SNOW_',1000000);


--bronze
CREATE OR REPLACE TASK DAGS.BRONZE_TB
AFTER DAGS.DADOS_BRUTOS
AS
    COPY INTO BRONZE.STAGING from @BRONZE.DADOS_BRUTOS PATTERN='.*SNOW_.*'
;

--SILVER
CREATE OR REPLACE TASK DAGS.SILVER_TRANSACOES
USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
AFTER DAGS.BRONZE_TB
WHEN
    SYSTEM$STREAM_HAS_DATA('BRONZE.STREAM_BRONZE_1')
as
insert into SILVER.TRANSACOES 
(select
    REGISTRO:card:number::varchar card_id,
    REGISTRO:merchant:id::varchar merchant_id,
    REGISTRO:transaction:id::varchar transaction_id,
    REGISTRO:transaction:amount::float amount,
    REGISTRO:transaction:currency::varchar currency,
    REGISTRO:transaction:approved::boolean approved,
    REGISTRO:transaction:type::varchar type,
    REGISTRO:transaction:timestamp::datetime timestamp
from BRONZE.STREAM_BRONZE_1
);


CREATE OR REPLACE TASK DAGS.SILVER_OPERACOES
USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
AFTER DAGS.BRONZE_TB
WHEN
    SYSTEM$STREAM_HAS_DATA('BRONZE.STREAM_BRONZE_2')
as
insert into SILVER.OPERACOES 
(CARD_ID, transaction_id, timestamp)
(select
    REGISTRO:card:number::varchar card_id,
    REGISTRO:transaction:id::varchar transaction_id,
    REGISTRO:transaction:timestamp::datetime timestamp
from BRONZE.STREAM_BRONZE_2
);


CREATE OR REPLACE TASK DAGS.SILVER_APROVACOES
USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
AFTER DAGS.BRONZE_TB
WHEN
SYSTEM$STREAM_HAS_DATA('BRONZE.STREAM_BRONZE_3')
as
insert into SILVER.APROVACOES  (transaction_id, approved, timestamp)
(select
    REGISTRO:transaction:id::varchar transaction_id,
    REGISTRO:transaction:approved::boolean approved,
    REGISTRO:transaction:timestamp::datetime timestamp
from BRONZE.STREAM_BRONZE_3
);



--GOLD
CREATE OR REPLACE TASK DAGS.GOLD_CONSOLIDACAO
AFTER DAGS.SILVER_APROVACOES
AS
insert into GOLD.APROVACOES_CONSOLIDADAS (status, contagem)
SELECT approved, COUNT(*) FROM SILVER.STREAM_APROVACOES GROUP BY approved
;


--HABILITA TASKS
ALTER TASK DAGS.BRONZE_TB RESUME;
ALTER TASK DAGS.SILVER_TRANSACOES RESUME;
ALTER TASK DAGS.SILVER_OPERACOES RESUME;
ALTER TASK DAGS.SILVER_APROVACOES RESUME;
ALTER TASK DAGS.GOLD_CONSOLIDACAO RESUME;
ALTER TASK DAGS.DADOS_BRUTOS RESUME;



--FORÇA EXECUÇÃO
EXECUTE TASK DAGS.DADOS_BRUTOS; 


LIST @BRONZE.DADOS_BRUTOS/;

--Acompanhamento Pós execução (STEAMS)
SELECT 'STREAM_BRONZE_1', COUNT(*) FROM BRONZE.STREAM_BRONZE_1
UNION 
SELECT 'STREAM_BRONZE_2', COUNT(*) FROM BRONZE.STREAM_BRONZE_2
UNION
SELECT 'STREAM_BRONZE_3', COUNT(*) FROM BRONZE.STREAM_BRONZE_3;

--Acompanhamento Pós execução (tabelas)
SELECT 'STAGING', COUNT(*) FROM BRONZE.STAGING
UNION
SELECT 'APROVACOES', COUNT(*) FROM SILVER.APROVACOES
UNION 
SELECT 'OPERACOES', COUNT(*) FROM SILVER.OPERACOES
UNION
SELECT 'TRANSACOES', COUNT(*) FROM SILVER.TRANSACOES
UNION 
SELECT 'APROV CONSOLIDADAS', COUNT(*) FROM GOLD.APROVACOES_CONSOLIDADAS;




--RESET
CREATE OR REPLACE STREAM BRONZE.STREAM_BRONZE_1 ON TABLE BRONZE.STAGING;
CREATE OR REPLACE STREAM BRONZE.STREAM_BRONZE_2 ON TABLE BRONZE.STAGING;
CREATE OR REPLACE STREAM BRONZE.STREAM_BRONZE_3 ON TABLE BRONZE.STAGING;

--SUSPENDE TASKS
ALTER TASK DAGS.DADOS_BRUTOS SUSPEND;
ALTER TASK DAGS.BRONZE_TB SUSPEND;
ALTER TASK DAGS.SILVER_TRANSACOES SUSPEND;
ALTER TASK DAGS.SILVER_OPERACOES SUSPEND;
ALTER TASK DAGS.SILVER_APROVACOES SUSPEND;
ALTER TASK DAGS.GOLD_CONSOLIDACAO SUSPEND;

--LIMPA STAGES
REMOVE  @BRONZE.DADOS_BRUTOS/;
LIST  @BRONZE.DADOS_BRUTOS/;


--LIMPA TODOS OBJETOS
TRUNCATE TABLE BRONZE.STAGING;
TRUNCATE TABLE SILVER.TRANSACOES;
TRUNCATE TABLE SILVER.OPERACOES;
TRUNCATE TABLE SILVER.APROVACOES;
TRUNCATE TABLE GOLD.APROVACOES_CONSOLIDADAS;

